on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
                  architecture: 'x64'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: PyInstaller
              run: python -m PyInstaller --clean -F --noupx --hidden-import artemisremotecontrol --hidden-import artemisremotecontrol.config --name ArtemisRemoteControl run.py
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ArtemisRemoteControl
                  path: dist/windows
