on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.7.5'
            - run: python setup.py build
            - run: python setup.py install

            - name: Package Application
              uses: JackMcKew/pyinstaller-action-windows@main
              with:
                  path: .

            - uses: actions/upload-artifact@v2
              with:
                  name: ArtemisRemoteControl
                  path: dist/windows
