on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Package Application
              uses: JackMcKew/pyinstaller-action-windows@main
              with:
                  path: .
                  python-version: '3.9'

            - uses: actions/upload-artifact@v2
              with:
                  name: ArtemisRemoteControl
                  path: dist/windows
